#include <iostream>
#include "Point.h"

int main(int argc, char **argv){

    //Deleted constructors

    //This is a method to disable any constructor? Maybe to
    //     1.)  Prevent users from creating objects in some way...
    //     2.)  Prevent copies of any kind...
    //     3.)  ^^ Disable anything that would typically be autogenerated? ^^ 
    
    //Basically you label the constructor '=delete;' at declaration

    //look at header file where I have implemented this with the default empty constructor

    Point pointA {}; //use of deleted function compiler error

    return 0;
}